### ISSUE TITLE
Script to change crate-type before build

### ISSUE THREAD

**Issue by adamski** [JanosGit/Resvg4JUCE#1]
I think instead of maintaining a fork whose only purpose is to change the crate type, I suggest a script that alters the `Cargo.toml` before calling `cargo build`

**Comment by JanosGit** [comment]
Yes, that's a good point. I think about creating a CMake based build instead of the current scripts and would probably join these two tasks.

Alternatively, is there any option to override it by some commands passed to cargo build? I didn't found any, but I'm also really no rust expert

**Comment by JanosGit** [comment]
Update: It should be possible to alter the crate type by using `cargo rustc` instead of `cargo build`. See here: https://stackoverflow.com/questions/65012484/is-it-possible-to-override-the-crate-type-specified-in-cargo-toml-from-the-comma

Will likely update the project in the next 2 weeks

**Comment by JanosGit** [comment]
I've changed the build to be completely CMake-based now, including triggering `cargo rustc` directly from within CMake so this should have solved the issue now – at least for all CMake users. Due to the complexity of triggering a rust build step that cannot be achieved with a Projucer based module solution I decided to not support Projucer based builds with this module anymore.
