### ISSUE TITLE
Scale factor in jb_SVGComponent is always 1

### ISSUE THREAD

**Issue by kauwua** [JanosGit/Resvg4JUCE#2]
Hi,

I'm using Resvg4JUCE in a VST3 plugin because JUCE's svg support is lacking some functionalities. I've run into an issue when dealing with the DPI scaling factor on Windows (I did not test this on macOS).

In the `resized()` method of _jb_SVGComponent_, `auto scale = juce::Desktop::getInstance().getDisplays().getDisplayForPoint (getBounds().getCentre())->scale;` is always 1 on my display, when the scaling factor should be 2.5. This is apparently intentional in JUCE according to this post for instance [Displays::Display::scale always 1.0 from within windows DAWs](https://forum.juce.com/t/displays-scale-always-1-0-from-within-windows-daws/41281). 

I've implemented the solution given in the above forum topic here https://github.com/Riuzakiii/Resvg4JUCE/commit/8e49fab7b53866d9c32dad5c23bff9027c64004b which seems to fix the problem.  Do you see any issues with this fix ?

Thanks

**Comment by JanosGit** [comment]
Thank you for bringing that up. I just did a quick test on macOS on my MacBook Pro with a high res Retina display. Here the current scale computation correctly returns a scale factor of 2.0 which is expected, while `getApproximateScaleFactorForComponent()` returns 1.0.

If I get all that right, the correct approach will probably be multiplying both scale factors to retrieve the overall correct scale factor? It's been a while since I wrote this code, but I vaguely remember that I also got non 1.0 scale factors on Windows in some scenarios, so I would at least want to do some tests if this addition would not break anything in my Windows test environment before adding this. Will try to test that as soon as possible

**Comment by kauwua** [comment]
I think multiplying the scale factors would be better indeed. I tested my plugin in Standalone mode, and the original scale factor `juce::Desktop::getInstance().getDisplays().getDisplayForPoint(getBounds().getCentre())->scale` was 2.5 and `getApproximateScaleFactorForComponent(this)` was 1 . It seems that the original code is working, except for hosted VST plugins on Windows.

Multiplying both of them would take into account the display scale factor, and the additional transforms applied to the component (like Desktop::getInstance().getGlobalScaleFactor(), or the scaling factor applied on VSTs on Windows) https://github.com/Riuzakiii/Resvg4JUCE/commit/0ff91eb34e9f45543254d24f586450988b455fcc .

**Comment by JanosGit** [comment]
Thanks for verifying that!

I just pushed an according change that should fix it https://github.com/JanosGit/Resvg4JUCE/commit/a87c33d4a9c999f0ca7c5026768e4f615d90bdd7
